"""Adds upvote count for upvote model class

Revision ID: 26a104ba6f5c
Revises: 3dab1acc3fa1
Create Date: 2022-05-07 23:12:23.924979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a104ba6f5c'
down_revision = '3dab1acc3fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('upvotes_user_id_fkey', 'upvotes', type_='foreignkey')
    op.drop_constraint('upvotes_pitch_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'upvotes', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_pitch_id_fkey', 'upvotes', 'pitches', ['pitch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('upvotes_user_id_fkey', 'upvotes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
