"""Adds bio and profile pic columns

Revision ID: 3bf3059fc5c0
Revises: 644b64aceff6
Create Date: 2022-05-08 12:41:42.444225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf3059fc5c0'
down_revision = '644b64aceff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'downvotes', ['id'])
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'downvotes', type_='unique')
    # ### end Alembic commands ###
